pion/sctp

association.go, association_test.go, go.mod, go.sum, stream.go
Some refinements for the stream reset PR:
- Added an E2E test for SCTP over UDP.
- Wait to reset the stream until we've received the last send packet indicated in the reset request.
- Make the read notification asynchronous so the association lock isn't locked for too long.
- Update the test dependency to a version that supports modules.
=> Stream reset refinements

association.go, association_test.go, payload_queue.go
Resolves #30
As discussed in #30, made the acceptCh a buffered channel with size 16. Write to the channel now will not block.
=> Prevent write to acceptCh from blocking

association.go, association_test.go, stream.go
This fixes the follow (related) problems:
(1) Bug with a comparison between senderLastTSN and peerLastTSN.
(2) for loop inside stream.ReadSCTP() has a multiple of lock/unlock phases, which is causing s.readErr was evaluated before checking reassembly queue when it acquires a lock again. Consequently, io.EOF was returned when there's a data in the reassembly queue.
(3) Related to (2), the condition variable was not associated with the mutex. Probably this is why multiple of lock/unlock were needed. (at least, read from the queue and evaluate error when no data, has to be atomic!)
(4) When sender side closes a stream and sends a reset, if there’s a DATA chunk in the pending queue (TSN not assigned yet), the data will be lost.
(5) There is only one instance of paramOutgoingResetRequest and …
=> Handle Close() correctly to cause EOF on remote

association.go
This is the log we have been seeing:
```
ortc ERROR: 2019/05/08 09:49:25 Failed to accept data channel: The association is closed
```
Currently, association.AcceptStream() returns errAssociationClosed and that is the only error it returns. This error returns only when association.Close() is called, and it is expected that AcceptStream() will also immediately return with the error. When SCTPTransport sees this error, it does log.Errorf() which has been annoying users.
A suggested solution is to return io.EOF instead to indicate "no more incoming stream", so that SCTPTransport can suppress the log when the error is io.EOF. 
Relates to pion/webrt#664
=> Switch errAssociationClosed to io.EOF

README.md, association_test.go, stream.go
If the reassemblyQueue returns an io.ErrShortBuffer, this error is
returned instead of being overwritten and lost
Since the datachannel read loop https://github.com/pion/webrtc/blob/master/datachannel.go#L292 is checking for io.ErrShortBuffer errors, the best thing to do is simply return this error from Stream.ReadSCTP
and let the calling functions handle it.
See https://trac.torproject.org/projects/tor/ticket/28942#comment:15
Fixes #50
=> Patch to properly return an io.ErrShortBuffer

README.md, association.go
Small optimization: prevent the execution of a string formatting operation for each log line
using association name.
=> Store association name

association.go, stream.go
Small optimization: prevent the execution of a string formatting
operation for each log line using stream name.
=> Store stream name

README.md, association.go, association_test.go
writeLoop routine can be leaked if the connection is lost when there is no writing packet.
So, writeLoop should also be stopped if readLoop is stopped.
And, closeWriteLoopCh should be closed, even if netConn.Close() returned error.
After running the system using webrtc.PeerConnection for a while on the real environment, pprof could find routine leaks.
```
goroutine profile: total 92
79 @ 0x42dcbb 0x43da76 0x78de46 0x45b161
#	0x78de45	github.com/pion/sctp.(*Association).writeLoop+0x1b5	/go/pkg/mod/github.com/pion/sctp@v1.6.4/association.go:426
2 @ 0x42dcbb 0x42dd63 0x404e8d 0x404c65 0x79b63b 0x7ab3f6 0x45b161
#	0x79b63a	github.com/pion/sctp.(*Association).onRetransmissionFailure+0x41a	/go/pkg/mod/github.com/pion/sctp@v1.6.4/association.go:2003
#	0x7ab3f5 …
```
=> Fix routine leak

association.go, payload_queue.go, payload_queue_test.go, vnet_test.go
Resolves #63
Now the lock-up with full-receiver buffer is fixed for unordered stream as well.
=> Fix rcv buff full lockup for unordered stream

association.go, association_test.go, pending_queue.go, pending_queue_test.go, reassembly_queue.go, vnet_test.go
Resolves #71
* Added a comparison between received data an original data transmitted to vnet_test.go
* Unordered message was found broken
* Potential reorder in the pendingQueue was not happening (which was fixed and unit-tested)
* found **reassmblyQueue had a bug in handling unordered chunk slices**
* fix was confirmed by the test
=> Fix unordered message corruption

association.go, association_test.go, chunk_payload_data.go, payload_queue.go, payload_queue_test.go, vnet_test.go
Relates to #62
* fix-1: Increase cwnd in slow-start by the current cwnd (to be comparable with TCP), and send immediateAck bit more frequently.
* fix-2: Fix bug with retransmission on t3-rtx timeout (was sending only one by the timeout)
* Increase the initial receive buffer size from 64KB to 1MB (to be comparable with TCP with RTT 160msec)
* Made ReceiveBufferSize configurable (from sctp.Config - defaults to 1MB)
* Add/fix tests.
See the issue #62 for details.
=> Improve throughput over network with delay

ack_timer.go, association.go, association_test.go, chunk_selective_ack.go
Relates to #62
SCTP implementation was not following the suggestion mentioned in RFC 4960 for generating SACK, causing the poor performance in receiving data from others (Browsers, etc)
By generating SACK at every second packet, as suggested by the RFC, improved the performance to close to the theoretical throughput.
See #62 for some benchmarks.
=> Improve handling of SACK

association.go, association_test.go, paramheader.go, vnet_test.go
See #45 
In addition to the retransmission of RECONFIG chunk, following bugs were found and also fixed:
* Reconfig was not handled in the case where TSN was forwarded
* The delayed ack handling resolved in #79 for DATA chunk was not applied to ForwardTSN chunk. (I have made a common routine for handleData() and handleForwardTSN())
* Added a test for RECONFIG retransmission
* Refactored a.gatherOutbound() for complexity error by golangci-lint
=> Retransmit RECONFIG

association_test.go
Some tests using net.Conn connection are disabled for now
as it is not fully supported by WASM MVP stage.
preparation for https://github.com/pion/.goassets/pull/4
=> Support WASM build/test

chunk_test.go
Avoid constant overflow.
Fix #94
ref: https://github.com/pion/sctp/pull/93
=> Fix 32bit test

association_test.go
Add lock to the stats data read.
Fix  #91
=> Fix data race in TestStats

association.go, association_test.go, chunk_abort.go, chunk_abort_test.go
Properly tear down the association when we receive an ABORT
chunk.
=> Tear down assocation on ABORT chunk

association.go, association_test.go, chunk_payload_data.go, payload_queue.go, reassembly_queue.go, reassembly_queue_test.go, stream.go
This PR fixes two issues:
* #104 Abort (ProtocolViolation) with FwdTSN for fragmented messages
* #106  Receive buffer leakage on FwdTSN for unordered data chunks
Test:
* pion/sctp unit tests pass with no race
* Ordered/Unordered data channel test (manual) with Chrome and Firefox
This PR replaces earlier PR #105.
=> Fix ProtocolViolation error from usrsctp and rwnd exhaustion

rtx_timer.go, rtx_timer_test.go
Resolves #109
The guard added allows doing the shift operation up to 30 bits and no more. (maxRTO can be up to 2^30 - large enough).
I added test to verify that next RTO values are capped at maxRTO even nRtos becomes larger than 63.
=> Guard shift-left operation

association.go
Resolves #112
Fix confirmed:
```
$ PION_LOG_DEBUG=sctp go test -v -run TestRoutineLeak/Close_failed |grep 'readLoop exited'
sctp DEBUG: 13:31:24.243066 association.go:434: [0xc0000b0000] readLoop exited EOF
```
=> Fix debug log format

payload_queue.go, payload_queue_test.go
Resolves #104
> Sorry... typo in the branch name... this is for issue 104.
Please read #104 for details.
When T3-rtx timeout occurs, it sets `retransmit` flag of all chunks in the inflightQueue to true. Immediately after that  (before the actual retransmission takes place by the writeLoop go-routne), SACK was received for some of these data chunks and their `acked` flag was set to true and userData was deleted (empty) without resetting `retransmit` flag. This ended up with sending DATA chunk with userData field being empty, causing the remote to send Abort chunk because sending DATA chunks with zero-length userData field is illegal according to RFC.
This branch reset the `retransmit` flag when SACK is received for a DATA chunk. I no longer see Abort coming back.
=> Reset retransmit flag when acked

README.md, association.go
* In my local testing reads from the underlying SCTP stream are rarely (if ever!)
sized at the receiveMTU amount.
* Typically they are around 30-700 bytes.
* This reduces the memory allocations by a fair whack.
May need more thorough testing.
=> Reduce allocations in association.readLoop

association.go, association_test.go, stream.go
Relates to pion/webrtc#1270
The flag in the association, "useForwardTSN" was not set correctly when INIT-ACK was not received due to a packet loss. The extension param for fowardTSN is also in the INIT chunk, and current pion/sctp does not extract the value. This PR add the missing code to correctly set "useForwardTSN" despite the loss of INIT-ACK.
=> extract useForwardTSN in handleInit

go.mod, go.sum, rtx_timer_test.go
Race conditions were detected with the variable `nCbs` used in rtx_timer_tests.go.
By using sync/atomic methods on the variable, the race was gone in my local environment after updating testify to v1.6.1.
Fixes #129
=> Fix race in rtx timer test

association.go
Relates to #138
Please see #138 for details.
This pull-request fixes a bug found during the trouble-shooting for #138. As the root cause of the hang addressed in #138 was not by this bug, but the current implementation obviously incorrect and this fix is necessary.
=> Use reliable transmission for dcep message

association.go, association_test.go, stream.go
* Modified the default maxMessageSize from 65535 to 65536.
* Added getter/setter function also.
Relates to pion/webrtc#1396
=> Set default MaxMessageSize to 65536

README.md, association.go, association_test.go, chunk_shutdown.go, chunk_shutdown_ack.go, chunk_shutdown_ack_test.go, chunk_shutdown_complete.go, chunk_shutdown_complete_test.go, chunk_shutdown_test.go, packet.go, stream.go
I finally had some time to continue the work on adding the multi server node support on `Peer Calls`. I noticed there was an issue where the other side did not notice that a SCTP association was closed from the other side.
I tried to follow the steps from the [`SCTP Association State Diagram`][1] and [`Shutdown of an Association`][2] sections of [RFC 4960][3].
I added two new tests and all existing tests passed.
Instead of modifying the existing `Close` function I added a new `Shutdown` method to keep the backwards compatibility. I also thought it made sense to allow the users to pick which teardown strategy to use.
Perhaps the `Close` should be modified to use `Abort`?
Fixes #152.
[1]: https://tools.ietf.org/html/rfc4960#section-4
[2]: https://tools.ietf.org/html/rfc4960#section-9.2
[3]: …
=> Implement shutdown sequence

association.go, association_test.go, chunk_payload_data.go
It caused panic when some kind of packets are arrived before completing initialization.
Add error check to CookieEcho and Data handlers.
Fixes #188
=> Fix packet handling before init

association.go, association_test.go, error_cause.go, error_cause_user_initiated_abort.go
According to [RFC 4960 Section 9.1](https://tools.ietf.org/html/rfc4960#section-9.1). Also see my comment at #176, more precisely: https://github.com/pion/sctp/pull/176#issuecomment-782578388
Closes #182.
I don't think we currently do any tag verification for any packets, but we can implement that later.
I _think_ that `Close` method should be modified to call `Abort("close")` or similar; I was unable to find any part of the spec that allows just closing the underlying connection.
=> Add sctp.Association.Abort(reason string) method

association.go, stream.go, vnet_test.go
When close datachannel from chrome, sctp should response with an outgoingResetRequest, otherwise the chrome won't fully close the datachannel.
Fixes #187
=> Fix Chrome datachannel stuck at closing

AUTHORS.txt, vnet_test.go
Fixes #242
Renaming an error object in a goroutine in TestStreamClose to avoid race error during test.
Occurrence ratio: ~ 1/5
=> Fix race in TestStreamClose introduced by #238

association_test.go, stream.go
Add a read-deadline method similar to net.Conn/net.PacketConn to allow read timeouts to be implemented
Fixes #240
=> stream: Add "SetReadDeadline"

association.go, chunk_payload_data.go, stream.go, vnet_test.go
=> Remove pending buffer when stream closed

association.go, chunk_payload_data.go, stream.go, vnet_test.go
This reverts commit c0159aa2d49c240362038edf88baa8a9e6cfcede.
@jerry-tao @enobufs, the reverted commit made sense in theory but it's causing a regression in what https://github.com/pion/webrtc appears to expect in terms of data channel closing behavior with respect to pending writes on the sender side. More specifically, `TestEOF/Detach` started to fail where we expected that when the sender did a write followed by close, that the reader would see those writes and then see an EOF. That is to say, the enqueued writes are lost due to these changes. It doesn't seem like this change fixed any correctness issues with regards to the spec so it seems like we should revert it so as to unblock other changes in this v1.8.x. v1.8.4 is currently published but is now broken/flaky. …
=> Revert "Remove pending buffer when stream closed"

association.go
The call to String was being executed unconditionally, even when
logging was disabled.  Fortunately, it's not needed.
This shaves some 10-15% off the time needed to do bulk receives.
=> Don't call String in call to Debugf

association.go, association_test.go
* Added reproducible leakage check along with a fix.
* Fixed a test case that had a goroutine that did not exit.
* Ubuntu linux appears to have a bug causing initial packet exchange to fail (see issue #270 for details). To workaround it, the test tool `createAssocs()` has been updated to use "dumbConn2" (similar to the existing "dumbConn" which uses test.Bridge.) instead of using kernel routing between the two net.Conn endpoints.
Fixes #270
=> [WIP] Fix goroutine leakage

chunk_init.go, chunk_init_common.go, chunk_init_test.go, param_ecn_capable_test.go, param_forward_tsn_supported_test.go, paramheader.go
Start to implement section-3.2.1 and respect chunks with a action of Skip. We don't properly report the values back yet.
=> Support Unknown Parameters in INIT Chunk

rtx_timer.go
This is the default in [RFC 9260](https://www.rfc-editor.org/rfc/rfc9260.html#section-16).
=> Reduce RTO.Initial to 1 second

association.go, association_test.go
Currently padding is not considered when decided how many chunks to bundle in to 1 packet. This causes some packets to exceed the MTU size. See the added test for a repro.
=> Consider padding when bundling chunks in packets

packet.go
Only the following packets should be accepted:
* Packets with a correct CRC32c checksum.
* Packets with an incorrect zero checksum, if its acceptance is allowed.
In particular, packets with an incorrect non-zero CRC32c must be discarded.
=> Fix checksum check for received packets

association.go, rtx_timer.go, rtx_timer_test.go
This change adds RTOMax to Config letting the user cap the retransmission timer without breaking compatibility. If RTOMax is 0 the current value of 60 seconds is used.
Start fixing #181, needs another PR in webrtc to support this feature
=> Configurable RTOMax - fix #181

stream.go
When a timer expires we should check if the timer has been cancelled. In busy systems, an old timer can trigger DeadlineExceeded error even when the caller had correctly updated the deadline. 
I'm observing this here, in my admittedly complicated use case.
https://github.com/libp2p/go-libp2p/actions/runs/7070633636/job/19247525950?pr=2615
I was observing this in my code and have since rewritten to ignore deadline exceeded errors from the library and do something adhoc in my code. Because some times a previously set deadline update could trigger a Deadline exceeded error. 
https://github.com/libp2p/go-libp2p/blob/sukun/webrtc-fin-ack/p2p/transport/webrtc/stream.go#L285-L290
=> check if deadline timer has been cancelled before signaling

association.go, association_test.go
zero checksum acceptance was implemented as a symmetrical feature, but this is not the way it is specified. Each side announces independently from the peer, that it can accept packets with an incorrect zero checksum. In particular, it is completely valid to send a packet containing an INIT ACK chunk with an incorrect zero checksum, as long as the peer announced the support in the INIT chunk.
=> Fix zero checksum usage

association_test.go, chunk_payload_data.go, reassembly_queue.go, reassembly_queue_test.go
This fixes a case where a chunk with the same SSN that is not fragmented is combined with a fragmented chunk. This can happen in a case where we send so many chunks that the SSN wraps.
=> Fix incorrect fragmented chunk merge

association.go
Inconsequential but follows the language of the RFC better
=> Go to COOKIE_WAIT after T1-init start

stream.go
At face value it looks like the error message from Stream.WriteSCTP() should report the exact maximum packet size it compared the actual packet size to.
=> Update WriteSCTP outbound packet too large error

go.mod
Part of changes required after https://github.com/pion/.goassets/pull/209. Related to https://github.com/pion/webrtc/issues/2292
=> Update go.mod to 1.19

association.go, association_test.go, payload_queue.go
We can only ACK TSN offsets 64k from the cummulativeTSN so there's no point queuing higher TSNs
=> Limit maximum tsn queued by the association

association.go
The SCTP implementation used in v3.2.28 fails to establish a connection with other WebRTC implementations. The implementation of ZeroChecksum assumes incorrectly that the feature is bi-directional
SCTP ZeroChecksum is actually a uni-directional feature which causes the Assocations to be unable to communicate.
=> Heuristics to fix interop with bad ZeroChecksum

association_test.go
This test was introduced in #323. Sometimes closing the stream will error with:
> sending reset packet in non-established state: state=Closed
I think it's okay to ignore this error as it's not related to the test.
=> Fix flaky test by ignoring error in stream close

chunk_payload_data.go, error_cause_header.go, param_requested_hmac_algorithm.go
Some chunks were not validated properly what could cause crash.
=> Fix SCTP chunk validation

packet.go
Fuzzers need some public function to perform their work.
=> Added TryMarshalUnmarshal for fuzzers

association.go
When remote resets its write half of the stream, we can still send messages on it. This is not an error condition.
=> Reduce log level to trace for expected case

association.go, association_test.go
Without this, there's a race between OpenStream and the readLoop unregistering streams. When the race happens, a stream is leaked and will get stuck in a read loop waiting forever.
=> Do not add streams after association is closed

association.go, association_test.go
Fixes:
```
panic: test timed out after 10m0s
running tests:
TestAssociation_createClientWithContext (9m30s)
goroutine 381 [running]:
testing.(*M).startAlarm.func1()
/usr/local/go/src/testing/testing.go:2366 +0x38c
created by time.goFunc
/usr/local/go/src/time/sleep.go:177 +0x2f
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0x8d42008, {0x82b13b0, 0x27}, 0x82bc794)
/usr/local/go/src/testing/testing.go:1750 +0x3d8
testing.runTests.func1(0x8d42008)
/usr/local/go/src/testing/testing.go:2161 +0x45
testing.tRunner(0x8d42008, 0x8d21dfc)
/usr/local/go/src/testing/testing.go:1689 +0x125
testing.runTests(0x8c10220, {0x845e660, 0x56, 0x56}, {0xc1a6b70d06f1a027, 0x8bb2d357fb, 0x8460720})
/usr/local/go/src/testing/testing.go:2159 +0x39d
testing.(*M).Run(0x8c16320) …
```
=> Unblock handshake ch on close

association.go, association_test.go
Although `OpenStream` checks state before creating a stream, `readLoop`'s `unregisterStream` can be called outside of a direct `Close`. When this happens, `setState(closed)` happens **after** unregisterStream which is an incorrect ordering causing an `OpenStream` to proceed. readLoop should set the closed state prior to unregistering streams.
Repro with carefully placed sleeps to mimic an internal close of connections being closed:
```
diff --git a/association.go b/association.go
index 29e9978..2cf2539 100644
--- a/association.go
+++ b/association.go
@@ -578,6 +578,7 @@ func (a *Association) readLoop() {
a.unregisterStream(s, closeErr)
}
a.lock.Unlock()
+		println("unregged")
close(a.acceptCh)
close(a.readLoopCloseCh)
@@ -650,6 +651,8 @@ loop:
}
}
+	time.Sleep(3 * time.Second)
+ …
```
=> set close state before unregisterStream

association.go, association_test.go
The loss-based congestion control get poor
performance under high bandwidth, high rtt
and packet loss case since the congestion
window becomes 1 mtu and increase slowly
after retransmit timeout. And fast recovery
retransmit cause exit slowly in consecutive
packet loss. This change add paramters to
the config then the user can set them to get
higher throughput in such cases.
Fixes #...
=> Add congestion control parameters to config

association.go, association_test.go, queue.go
According to the [RFC4960](https://datatracker.ietf.org/doc/html/rfc4960#section-7.2.4) , the missing indications should be incremented for missing chunks in the SACK.
> If an endpoint is in Fast
>    Recovery and a SACK arrives that advances the Cumulative TSN Ack
>    Point, the miss indications are incremented for all TSNs reported
>    missing in the SACK.
=> Increment missing indications from SACK

association.go, association_test.go, stream.go
Block write is useful for cases like sfu to forward reliable message between clients and detach the data channel to use it as normal golang connections. The default behavior is still non-block mode and the user need to enable block mode by the config. Will also add an SettingEngine option to pion/webrtc for this.
Relates to #77  and #314
=> Add blocking write mode for association

stream.go
Return 0 written bytes on write error
Fixes #...
=> Return 0 written bytes on write error

association.go
The rwnd has not been initialized from InitChunk
then payload data will be hold in the pending
queue until first SACK is received.
=> Set rwnd from InitChunk

association_test.go, reassembly_queue.go, reassembly_queue_test.go, stream.go
Currently if the user passes a buffer to read into that is shorter then the current message we lose the buffer. This PR changes the behavior to instead keep what's in the reassemblyQueue until it can be read.
Relates to pion/webrtc#2712
=> Don't discard data on io.ErrShortBuffer

ack_timer_test.go, association_test.go, chunk_forward_tsn_test.go, chunk_init_test.go, chunk_reconfig_test.go, chunk_shutdown_ack_test.go, chunk_shutdown_complete_test.go, chunk_shutdown_test.go, chunk_test.go, chunktype_test.go, packet_test.go, param_ecn_capable_test.go, param_forward_tsn_supported_test.go, param_outgoing_reset_request_test.go, param_reconfig_response_test.go, param_test.go, paramheader_test.go, paramtype_test.go, payload_queue_test.go, receive_payload_queue_test.go, rtx_timer_test.go, util_test.go, vnet_test.go
Use testify/assert in place of the standard testing package, and update where applicable to use `assert.NoError`
pion/.goassets/pull/222
N/A
=> Enforce testify/assert for tests

association.go, association_test.go
It simplifies tracking amount of unsent data for all data channels, including ones in closing state. Especially useful for IoT apps which use multiple data channels and have to monitor memory usage.
I will create another PR in `pion/webrtc` to add `SCTPTransfer.BufferedAmount` there.
=> Make Association.BufferedAmount public

vnet_test.go
Removes a deprecated call to `rand.Read()` from the math module in favor of `rand.Read()` from crypto. Also uses testify/require to make some of the `if !assert... { return }` blocks more intuitive/easier to read.
N/A
=> VNet remove deprecated rand.read(), improve test readability

association_test.go
`rand.Seed(time.Now().UnixNano())` used to be necessary since the rng value would begin at 1, but that isn't the case anymore. So we can remove it since it's automatically randomized. I believe the resulting behavior of the tests should remain the same.
N/A
=> Association tests: Remove rand.seed()
