pion/sctp

.github/assert-contributors.sh, .github/lint-commit-message.sh, .github/lint-disallowed-functions-in-library.sh, .golangci.yml, .travis.yml, README.md, chunk_test.go, go.mod, go.sum, param_reconfig_response.go, param_reconfig_response_test.go, reassembly_queue_test.go, stream.go
=>  CI: Setup CI

association.go
Currently we block until assocation is finished, but if the readloop
is already done the assocation is never going to finish.
Closes #15
=> Return from Server/Client if doneCh is closed

stream.go
=> Fix race when send buffer is reused

association.go
Fixes race found in pions/webrtc CI
Resolves #28
=> Lock stream when accessing it in assocation

README.md, association.go, association_test.go, go.mod, go.sum
Pions organization was renamed to pion
=> Mass replace pions -> pion

.github/lint-disallowed-functions-in-library.sh, README.md, association.go, association_test.go, chunk_payload_data.go, go.mod, go.sum, payload_queue.go, payload_queue_test.go, pending_queue.go, pending_queue_test.go, reassembly_queue.go, rtx_timer.go, rtx_timer_test.go, stream.go, stream_test.go
Basic implemention is done. Working on adding more tests right now.
Open issue: how to report T3-rtx retranmission failure to ULP?
See my [implementation note](https://docs.google.com/document/d/18HxKodWkPPfZpKTddQQvepux5MOS3QWMfK1eJYXQdz4) for your review
Resolves #11
=> [WIP] Implement T3-rtx timer and Congestion Control

association.go
I added a code to clean up timers when exiting writeLoop in this PR branch, no longer see a node firing rtx timeout after writeLoop exits.
I see other logs @bakkem saw is an isolated issue (association unintendedly running for a long time for the tests.)
As the cleanup of timers when writeLoop exits is clearly critical, let it land first.
Fixes #42
=> Write loop

go.mod, go.sum
Relates to pion/webrtc#652
Fixes #...
=> Cleanup dependencies

association.go, association_test.go
=> Add basic transport stats

association.go
=> Align for 32 bits

.golangci.yml, .travis.yml, chunk_error_test.go, chunk_init.go, chunk_init_ack.go, stream.go, stream_test.go
Fixed the tests accordingly
Resolves #59
=> Fix bufferedAmount threshold checks

.golangci.yml, vnet_test.go
Also fixes lint error I saw on my pc..
=> Remove godox from .golangci.yml

stream.go, vnet_test.go
Resolves #65
* Unblock Read (ReadSCTP) on stream.Close
* Optimized the mutex lock/unlock using immediate function invocation
* Wrote a test to very the fix.
=> Unblock stream.Read on stream.Close

.travis.yml, README.md, examples/ping-pong/Makefile, examples/ping-pong/README.md, examples/ping-pong/conn.go, examples/ping-pong/ping.go, examples/ping-pong/pong.go
* Add a ping pong example with a readme on how to build and run it
Fixes #84
=> Add ping pong example

.golangci.yml, packet_test.go
Fix golint error.
Disable godox.
preparing pion/.goassets#4
=> Upgrade golangci-lint to 1.19.1

AUTHORS.txt, association.go, association_test.go, chunk_payload_data.go, examples/ping-pong/ping.go, stream.go, vnet_test.go
This allows negotiated channels to be fetched when created
out of band of SDP.
=> Add Assocation.GetOrOpenStream

.github/workflows/test.yaml
Update lint scripts and CI configs.
=> Update CI configs to v0.6.9

.github/workflows/test.yaml
Update lint scripts and CI configs.
=> Update CI configs to v0.6.10

examples/ping-pong/ping.go, examples/ping-pong/pong.go
This allows Wireshark to detect SCTP automatically.
=> Use IANA assigned UDP port number for SCTP/UDP

association.go, association_stats.go, association_test.go
This helps for debugging and is relatively low cost
=> Add SACKs sent and packets stats

go.mod
=> Update go.mod version to 1.19

.golangci.yml, chunk_test.go, vnet_test.go
Update lint rules, force testify/assert for tests
https://github.com/pion/.goassets/pull/222
https://github.com/pion/sctp/pull/366
=> Update lint rules, force testify/assert for tests

association_test.go
Replace interface{} with any
https://github.com/pion/.goassets/pull/231
https://github.com/pion/sctp/pull/375
=> Replace interface{} with any

association.go
Applies go modernization suggestions, see https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize for more details.
N/A
=> Apply go modernize
